services:
  - type: web
    name: student-dashboard-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.2
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
